### ISSUE TITLE
About loss

### ISSUE THREAD

**Issue by 704051419** [j96w/DenseFusion#113]
您好，我直接用中文说可能解释的比较清楚。关于loss 的问题
`pred = torch.add(torch.bmm(model_points, base), points + pred_t)`
在看了 #7 后我也没有很理解您的意思，这个RGBD得出的point不是绝对坐标么？他和gt的model_points不在一个坐标系下么，那么这样相加的几何意义是什么，我没太理解。
另外关于per-pixel的意义，其实在计算时也只是简单的在pixel上对每个点进行重复，如
` model_points = model_points.view(bs, 1, num_point_mesh, 3).repeat(1, num_p, 1, 1).view(bs * num_p, num_point_mesh, 3) 
  target = target.view(bs, 1, num_point_mesh, 3).repeat(1, num_p, 1, 1).view(bs * num_p, num_point_mesh, 3)`
这样对于计算有什么帮助呢？
谢谢，期待您的回复！

I was asking what's the meaning of this line of code `pred = torch.add(torch.bmm(model_points, base), points + pred_t)`. In addition, I also didn't understand these lines of code ` model_points = model_points.view(bs, 1, num_point_mesh, 3).repeat(1, num_p, 1, 1).view(bs * num_p, num_point_mesh, 3) 
  target = target.view(bs, 1, num_point_mesh, 3).repeat(1, num_p, 1, 1).view(bs * num_p, num_point_mesh, 3)`.

**Comment by 704051419** [comment]
是可以理解成points+pred_t才是实际的translation么？，而pred_t只是一个偏移量？

**Comment by j96w** [comment]
Hi, yes, `points+pred_t` is the absolute trans and `pred_t` is an offset translation based the location of the selected input point. Since our model is outputting `pred_t`, when we calculate the loss of the translation estimation, we need to add the point location `points` to it. This is why we do `pred = torch.add(torch.bmm(model_points, base), points + pred_t)`.

I think you miss understand the meaning of `model_points`. This is the pointcloud of the object mesh model which later used for loss calculation by rotating and translating with our predicted 6D pose. The repeating action is to expand the vector to the same size of our pose prediction so that we later can do calculation easily. `target` is also the pointcloud of object mesh model but is transferred by the GT 6D pose.

It would be better to use English to ask the issue so that ppl can know what we are discussing. Thank you.

**Comment by 704051419** [comment]
@j96w Thanks for your replying and translation. I seem to know your point.
You said,`new_points = torch.bmm((points - ori_t), ori_base).contiguous()`and `new_target = torch.bmm((new_target - ori_t), ori_base).contiguous()` are inverse operation to return the point to the origin. but as an inverse operation, the`ori_base` doesn't need to be inversed. why?

**Comment by j96w** [comment]
Because R^{-1} = R^T and (R^T * points)^T = (points^T * R). Here we are doing (points^T * R). The `points` is a (N * 3) matrix.

**Comment by 704051419** [comment]
Thanks!
and in `loss_refiner.py`,is it okay to just take the first Pose estimation like : `t = ori_t[0]`and `ori_base = ori_base[0].view(1, 3, 3).contiguous()`? 
i mean, there are 500 `pred_r, pred_t`, how to select without the confidence in `loss.py`?

**Comment by j96w** [comment]
No, you don't need to do that. Because the refiner only has one output and the `num_p` is already set to 1 in the `loss_refiner.py`.
