### ISSUE TITLE
cannot get good result with real data

### ISSUE THREAD

**Issue by kaixin-bai** [j96w/DenseFusion#117]
i have tested densefusion with real data, which got from realsense D415, but the result seems not as good as the evaluate data. Has somebody also tested it with real data, because i cannot find out where is wrong.
here are the segmentation result, cropped image, masked point cloud, visualization of 6d pose without and with refinement network.
![Screenshot_2019-11-07_16-43-56](https://user-images.githubusercontent.com/38804949/68403808-d38d1600-017d-11ea-9369-eec36dae604b.png)

**Comment by j96w** [comment]
Hi, could you make sure the segmentation is not missing the most important part of the object? In your case, the head of powerdrill is missing and this is probably why it 180° rotated because it regards the back as the head. I would suggest trying more different poses. BTW, I'm not sure whether applying the trained weight to different cameras with different intrinsics will affect the result. Haven't tested on realsense yet.

**Comment by kaixin-bai** [comment]
Thanks a lot for your answer, actually i didn't notice that the objects are not the same at the first. Now i got it.

**Comment by TONG369** [comment]
> Thanks a lot for your answer, actually i didn't notice that the objects are not the same at the first. Now i got it.


Hello ~ Excuse me, ask you a question, in what way are the pictures you show visualized? Please tell me and I am looking forward to your reply. Thankyou

**Comment by lalaLin997** [comment]
@kaixin-bai 
Could  you provide the the detail about how you visualize th3 four pictures?
Thank you in advance!

**Comment by kaixin-bai** [comment]
@TONG369 @lalaLin997 i use open3d to visualize the point cloud.
