### ISSUE TITLE
Segmentation results of LINEMOD dataset

### ISSUE THREAD

**Issue by cvchanghao** [j96w/DenseFusion#152]
Hi, Thanks for sharing your work.
I'm wondering how you got the segment results of LINMOD dataset. As we know that only one object's mask per frame. Even in 02 folder, the masks are still not enough. So how to train the SegNet with LINEMOD? Or you train one SegNet for each of the models?

**Comment by j96w** [comment]
Hi, yes, we train one SegNet for each model since the released LineMOD dataset only contains the pose label of one object in each video. We generate the segmentation ground truth by projecting the object model transformed by the ground truth pose to the image space. Since LineMOD is a small dataset, we also add synthetic data generated by [sixd_toolkit](https://github.com/thodan/sixd_toolkit). Basically, we randomly sampled the object pose and use sixd_toolkit to render the rgb image and use COCO as the background. Note that, these synthetic data are only used for the training of the segmentation model, the training of the pose estimation model didn't use these synthetic data.
