### ISSUE TITLE
confusion about get_bbox function

### ISSUE THREAD

**Issue by huipengly** [j96w/DenseFusion#31]
The code is in `eval_ycb.py`, and `datasets/ycb/dataset.py`.

I think it inputs the roi from the semantic segmentation, and makes the new width(height) be the the smallest value in `border_list` not less than the old one(like ceil function). The output roi will only have fixed choice.

Why don't use the rois from segmentation?

Thank you and looking forward to your reply.

```python
border_list = [-1, 40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480, 520, 560, 600, 640, 680]
def get_bbox(posecnn_rois):
    rmin = int(posecnn_rois[idx][3]) + 1
    rmax = int(posecnn_rois[idx][5]) - 1
    cmin = int(posecnn_rois[idx][2]) + 1
    cmax = int(posecnn_rois[idx][4]) - 1
    r_b = rmax - rmin
    for tt in range(len(border_list)):
        if r_b > border_list[tt] and r_b < border_list[tt + 1]:
            r_b = border_list[tt + 1]
            break
    c_b = cmax - cmin
    for tt in range(len(border_list)):
        if c_b > border_list[tt] and c_b < border_list[tt + 1]:
            c_b = border_list[tt + 1]
            break
    center = [int((rmin + rmax) / 2), int((cmin + cmax) / 2)]
    rmin = center[0] - int(r_b / 2)
    rmax = center[0] + int(r_b / 2)
    cmin = center[1] - int(c_b / 2)
    cmax = center[1] + int(c_b / 2)
    if rmin < 0:
        delt = -rmin
        rmin = 0
        rmax += delt
    if cmin < 0:
        delt = -cmin
        cmin = 0
        cmax += delt
    if rmax > img_width:
        delt = rmax - img_width
        rmax = img_width
        rmin -= delt
    if cmax > img_length:
        delt = cmax - img_length
        cmax = img_length
        cmin -= delt
    return rmin, rmax, cmin, cmax
```

**Comment by j96w** [comment]
Hi @huipengly, yes, your understanding about what this function is doing is correct. So since we want to fuse each point on the pointcloud(generated from the depth) with its corresponding color embedding, we need to make sure that the encoder-decoder network won't change the width and height of the input rgb crop(input rgb crop: H * W * 3, output color embedding should be H * W * d) so that we can use the correspondence relationship(generated during the data preprocess, named `choose`) to realize the dense fusion idea. By resizing the rois into some limit choices (40, 80, 120, ...), we can easily make it instead of using a lot "if" codes or do padding during the network forward process. Secondly, since we plan to realize the batch training but the size of each rois are different, we are thinking to do some buffering idea that will pile the training samples with the same choice of size into one batch. We leave this part as a future enhancement.

**Comment by huipengly** [comment]
Many thanks.

**Comment by WilliamKRobert** [comment]
Does the get_bbox output index of bounding box? It seems that r_max should be img_width-1 instead of img_width (same for the c_max)?
