### ISSUE TITLE
About image normalization

### ISSUE THREAD

**Issue by xftao** [j96w/DenseFusion#39]
The documents of "torvision.model" have said that
` The images have to be loaded in to a range of [0, 1] and then normalized using mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225].`

The cropped image have been directly normalized without scaled into [0, 1]。
Is there any bug though it work?

**Comment by j96w** [comment]
Hi, yes there's a bug but seems like the network can handle it quite well.

**Comment by greatwallet** [comment]
> Hi, yes there's a bug but seems like the network can handle it quite well.

Hi! 

So have you tried the standard way? For instance:
1. Scale the RGB image to [0., 1.] and then normalize using mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225]?
2. Scale the RGB image to [0, 1] w/o ImageNet's normalization
3. Do neither, so that the RGB would be in range [0, 255].

The current dataloader gives out RGB in a really weird range, which bothers me a lot.
<img width="208" alt="捕获" src="https://user-images.githubusercontent.com/30019142/80702371-8a59c580-8b13-11ea-89ec-5c0bbca94982.PNG">
The above is visualization of the processed tensor from `Linemod_preprocessed/data/01/rgb/0001.png` using your dataloader pipeline. And its value range is [-2.1179, 1029.3066] w/o color-jittering. And this weirdly-ranged tensor is directly fed into network, which seems to be making little sense.

So should DenseFusion be working any better if I fix this to the standard way?

Thanks!
