### ISSUE TITLE
Is it possible to train SegNet on LineMod instead of YCB Video dataset?

### ISSUE THREAD

**Issue by TrinhTUHH** [j96w/DenseFusion#57]
The YCB Video dataset is quite big so I am wondering if I can use LineMod to train SegNet instead?

**Comment by BarbeBleue** [comment]
> The YCB Video dataset is quite big so I am wondering if I can use LineMod to train SegNet instead?

You can train SegNet with any dataset fwith labelled images but I don't really understand why you want to do it. YCB Video and Linemod are not based on the same object collection so the result will be totally different.  In order to have the best result you will need as much data as you can get so even if you want a smaller dataset I don't advise to try training with a sample of data from YCB but you can do it.

**Comment by TrinhTUHH** [comment]
@BarbeBleue thank you for replying. I want to do it since it is stated in the guide that SegNet is trained with YCB Video only, as in:
`python train.py --dataset_root=./datasets/ycb/YCB_Video_Dataset`
or is it just an example? As my understanding, if I trained the main model with LineMod, then it should be "Linemod" in the dataset_root instead of "YCB_Video".

**Comment by j96w** [comment]
> @BarbeBleue thank you for replying. I want to do it since it is stated in the guide that SegNet is trained with YCB Video only, as in:
> `python train.py --dataset_root=./datasets/ycb/YCB_Video_Dataset`
> or is it just an example? As my understanding, if I trained the main model with LineMod, then it should be "Linemod" in the dataset_root instead of "YCB_Video".

It's just an example. For Linemod, change to "Linemod".
