### ISSUE TITLE
Camera Distance

### ISSUE THREAD

**Issue by ghavidelsahar** [j96w/DenseFusion#60]
If the distance of the camera is higher than one meter, should we change the metric?
For instance in my dataset, camera distance is in range 1050 to 1100. Can I divide cloud points by 1200?
https://github.com/j96w/DenseFusion/blob/584efd68810c4d2f818207f2719a6ae886aac825/datasets/linemod/dataset.py#L153

**Comment by j96w** [comment]
Hi, I think it depends on whether you want to (1) Train on your own dataset from scratch or just (2) Test the model trained on Linemod to see whether it also works in your settings. For (1), nothing needs to change since the metric is still meter but just a little bit harder. For (2), I suggest you to divide and make the distance close to the settings of Linemod.

**Comment by ghavidelsahar** [comment]
Thanks!
