### ISSUE TITLE
Why the test set is bigger than train set in LineMod?

### ISSUE THREAD

**Issue by TrinhTUHH** [j96w/DenseFusion#75]
When checking the train.txt and test.txt in Linemod preprocessed dataset I notice that the test set (around 1200 samples per object) in LineMod is much bigger than the train set (aroung 200 samples per object).

My understanding is that it should be the other way around, right?

**Comment by hygxy** [comment]
But the test dataset is only choosen one out of ten, see [this line](https://github.com/j96w/DenseFusion/blob/master/datasets/linemod/dataset.py#L48), so the network is given more train data than test data, it's an expected behavior.

As why the author made the test dataset larger than the train dataset, I have the same question.

**Comment by flowtcw** [comment]
The protocol defined by [YOLO6D](https://github.com/microsoft/singleshotpose) and BB8, they use 15% of data for training and the rest 85% for evaluation. You can understand this as a default way.

**Comment by TrinhTUHH** [comment]
It is stated in [BB8](https://arxiv.org/pdf/1703.10896.pdf):
"Training images are selected such that the associated object poses have a minimum angular distance of 15◦. Doing so selects ≈ 15% of the images for training"
