### ISSUE TITLE
The pose result predicted in Pointfusion

### ISSUE THREAD

**Issue by YongLD** [j96w/DenseFusion#84]
Can you provide the pose result predicted with PointFusion(the .mat file)? I would like to compare with PointFusion, but cannot train the model in PointFusion.

**Comment by j96w** [comment]
Hi, it's not too difficult to convert DenseFusion to PointFusion. Basically, you only need to first replace the pspet to a vanilla ResNet and get a global feature output from it. Then, instead of dense fuse the embedding in a per-point level, you just need to repeat the global feature to n times and then concat them to the output of the pointnet. That's it.
